### PR TITLE
README: Add build hint for Ubuntu

### PR DESCRIPTION
**Pull request by tjvr**
Hey! 👋 It took me a little while to find the appropriate packages: I needed ` libusb-1.0-0-dev` and was also missing `pkg-config`. I thought I might try and save future readers the time!

### CODE REVIEW

**Comment by lurch** [comment]
I'm not sure about the addition of the `$` symbols - maybe they'd make it harder for people to copy'n'paste?

**Comment by tjvr** [comment]
Fair enough!

**Review by lurch — APPROVED** [review]
LGTM

**Comment by lurch** [comment]
On MacOS I needed to do `brew install libusb pkg-config` so perhaps "You also need to install `libusb-1.0`" should be changed to "You also need to install `libusb-1.0` and `pkg-config`" ?

**Review by kilograham — APPROVED** [review]

**Pull request merged**
