### PR TITLE
Don't write more data than will fit in flash

### PR DESCRIPTION
**Pull request by lurch**
Updated version of #19

### CODE REVIEW

**Comment by lurch** [comment]
The previous version of this PR (#19) got (accidentally?) auto-closed _again_ when the `develop` branch disappeared :confused: 

I had a quick check, and AFAICT it **looks** like none of the other PRs got auto-closed because they're all based against the `master` branch rather than the `develop` branch?  (but I didn't do a similar check for the `pico-sdk` or `pico-examples` repos, because there's lots of churn going on there and I've not been keeping up, so I wouldn't know which PRs are closed deliberately and which are closed accidentally)

**Comment by kilograham** [comment]
ah yes; i need to make develop not disappear!

**Comment by lurch** [comment]
@kilograham Bump, `develop` still isn't a protected branch :wink:

**Comment by will-v-pi** [comment]
Thanks, this has been merged for picotool 2.0.0 - and `develop` branch is now protected too

**Pull request closed without merging**
