### PR TITLE
MSYS2 / MinGW support

### PR DESCRIPTION
**Pull request by DavidEGrayson**
I like to use MSYS2 and its MinGW GCC toolchain for all my open source work; it really is a pleasure because it lets you compile native Windows software from an environment with all the usual Linux utilities, where everything works almost like Linux does.  With MSYS2, you don't have to do a bunch of special work to get your code compiling on Windows.

This pull request makes all the changes necessary to get this building with MinGW in MSYS2.  I don't think it will break anything for users of MSVC, but I haven't tested it with MSVC.

### CODE REVIEW

**Comment by kilograham** [comment]
cool thx, we'll obviously try it on Windows before building which means pain/delay :-)

**Comment by ndabas** [comment]
I don't think these changes are needed at all, I've been building picotool on Windows with MSYS2 + MinGW GCC just fine with the standard build commands:

```
pacman -S --noconfirm --needed autoconf automake mingw-w64-x86_64-cmake git libtool make mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain mingw-w64-x86_64-libusb mingw-w64-x86_64-hidapi pkg-config wget

cd picotool
mkdir -p build
cd build
cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

The first `pacman` command might have some stuff which isn't needed by `picotool`, I'm using the build environment for a few other things as well.

**Comment by ndabas** [comment]
@DavidEGrayson I found the missing piece: I had added this line to my build script, which should make it all work:

```
export LIBUSB_ROOT="/mingw64"
```

**Comment by DavidEGrayson** [comment]
OK.  I think it's better to use pkg-config to find libraries instead of requiring users to add environment variables, hence the pull request.

Even if we convince the CMake scripts to find libusb, there are still some problems in the code:

```text
$ export LIBUSB_ROOT=/mingw64
$ cmake --build .
[3/4] Building CXX object CMakeFiles/picotool.dir/main.cpp.obj
C:/Users/david/Documents/picotool/main.cpp:57: warning: "ERROR_CANCELLED" redefined
   57 | #define ERROR_CANCELLED -10
      |
In file included from C:/msys64/mingw64/include/winbase.h:2811,
                 from C:/msys64/mingw64/include/windows.h:70,
                 from C:/msys64/mingw64/include/libusb-1.0/libusb.h:64,
                 from C:/Users/david/Documents/picotool/picoboot_connection/picoboot_connection.h:13,
                 from C:/Users/david/Documents/picotool/picoboot_connection/picoboot_connection_cxx.h:10,
                 from C:/Users/david/Documents/picotool/main.cpp:30:
C:/msys64/mingw64/include/winerror.h:418: note: this is the location of the previous definition
  418 | #define ERROR_CANCELLED __MSABI_LONG(1223)
      |
[4/4] Linking CXX executable picotool.exe
```

This error is fixed in my pull request, by one of the lines I change in `main.cpp`.

**Comment by ndabas** [comment]
@DavidEGrayson agreed, this PR is the clean way of doing it.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
